=== aragoncg/dicom-storage-abastraction/dcm4chee-2.14.2/dcm4jboss-web/src/etc/conf/dcm4chee-web/dcm4chee-webroles-cfg.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
This is the XML DTD for the dcm4chee web roles config (WEB) descriptor.

<dcm4chee-webroles-cfg>
    <roles>
        <role name="WebAdmin" descr="Admin Web role" dependency="WebUser" /> 
        <role name="WebUser" descr="General Web User role"/> 
    </roles>
    <actions>
        <action name="Q" descr="Query"/> 
        <action name="R" descr="Read"/> 
        <action name="E" descr="Export"/> 
        <action name="A" descr="Append"/> 
        <action name="U" descr="Update"/> 
        <action name="D" descr="Delete"/> 
    </actions>
</dcm4chee-webroles-cfg>

-->

<!ELEMENT dcm4chee-webroles-cfg (roles,actions)>

<!ELEMENT roles (role+)>
<!ELEMENT role EMPTY>
<!ATTLIST role name CDATA #REQUIRED>
<!ATTLIST role display CDATA #IMPLIED>
<!ATTLIST role type CDATA #IMPLIED>
<!ATTLIST role descr CDATA #REQUIRED>
<!ATTLIST role dependency CDATA #IMPLIED>

<!ELEMENT actions (action+)>
<!ELEMENT action EMPTY>
<!ATTLIST action name CDATA #REQUIRED>
<!ATTLIST action descr CDATA #REQUIRED>

=== aragoncg/dicom-storage-abastraction/dcm4chee-2.14.2/dcm4jboss-web/src/etc/conf/dcm4chee-web/dcm4chee-webroles-cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dcm4chee-webroles-cfg SYSTEM "dcm4chee-webroles-cfg.dtd">
<dcm4chee-webroles-cfg>
    <roles>
        <role name="WebUser" descr="A user in this role is allowed to use this web interface."/> 
        <role name="WebAdmin" dependency="WebUser" descr="This role is used to allow access to AET and User management."/> 
        <role name="DatacareUser" dependency="WebUser" descr="A user in this role has Datacare rights (edit/merge/delete) in the web interface."/> 
        <role name="McmUser" dependency="WebUser" descr="This role is used to allow access to the Media Creation Console (Offline Storage)."/> 
        <role name="JBossAdmin" descr="This role is used to allow configuration access via JMX console."/> 
        <role name="AuditLogUser" descr="Members of this role are allowed to access the Audit Repository."/> 
        <role name="GrantPrivileg" descr="Members of this role are allowed to grant Study Permissions."/> 
        <role name="GrantOwnPrivileg" descr="Members of this role are allowed to grant Study Permissions."/> 
        <role name="Doctor" type="StudyPermission" descr="Sample Study Permission Role."/> 
    </roles>
    <actions>
        <action name="Q" descr="Query"/> 
        <action name="R" descr="Read"/> 
        <action name="E" descr="Export"/> 
        <action name="A" descr="Append"/> 
        <action name="U" descr="Update"/> 
        <action name="D" descr="Delete"/> 
    </actions>
</dcm4chee-webroles-cfg>
